name: Compile CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ rice ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: lineage-18.1

      # Compile the kernel
      - name: Compile the kernel
        env:
          BOT_TOKEN : ${{secrets.BOT_TOKEN}}
          CHAT_ID : ${{secrets.CHAT_ID}}
        run: ./.github/workflows/build.sh
